export const data={
    "login": "manojmogal007",
    "id": 107462443,
    "node_id": "U_kgDOBme_Kw",
    "avatar_url": "https://avatars.githubusercontent.com/u/107462443?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/manojmogal007",
    "html_url": "https://github.com/manojmogal007",
    "followers_url": "https://api.github.com/users/manojmogal007/followers",
    "following_url": "https://api.github.com/users/manojmogal007/following{/other_user}",
    "gists_url": "https://api.github.com/users/manojmogal007/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/manojmogal007/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/manojmogal007/subscriptions",
    "organizations_url": "https://api.github.com/users/manojmogal007/orgs",
    "repos_url": "https://api.github.com/users/manojmogal007/repos",
    "events_url": "https://api.github.com/users/manojmogal007/events{/privacy}",
    "received_events_url": "https://api.github.com/users/manojmogal007/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Manoj Mogal",
    "company": null,
    "blog": "https://manojmogal007.github.io/",
    "location": "Nashik,Maharashtra",
    "email": null,
    "hireable": true,
    "bio": "Proficient MERN developer",
    "twitter_username": null,
    "public_repos": 7,
    "public_gists": 0,
    "followers": 5,
    "following": 3,
    "created_at": "2022-06-14T07:16:00Z",
    "updated_at": "2022-12-02T06:49:14Z"
  }